### ISSUE TITLE
Build failing on update to openthread/openthread@876aa82

### ISSUE THREAD

**Issue by jwhui** [openthread/ot-qorvo#210]
The submodule update PR is failing:

- #209

I've narrowed it down to this commit:

- https://github.com/openthread/openthread/commit/876aa821645f2cf01574dc2faca2225b7bf1352e

Build logs:

```
[557/562] Linking CXX executable bin/ot-cli-mtd
FAILED: bin/ot-cli-mtd 
: && /tmp/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-g++  -mcpu=cortex-m4 -mthumb -fdata-sections -ffunction-sections -fno-exceptions -fno-rtti -Os -DNDEBUG  -mcpu=cortex-m4 -mthumb -fdata-sections -ffunction-sections -specs=nano.specs -specs=nosys.specs lib/examples/apps/cli/CMakeFiles/ot-cli-mtd.dir/cli_uart.cpp.obj lib/examples/apps/cli/CMakeFiles/ot-cli-mtd.dir/main.c.obj  -o bin/ot-cli-mtd  lib/libopenthread-cli-mtd.a lib/libopenthread-qpg6095-mtd.a lib/libopenthread-mtd.a lib/libopenthread-qpg6095-mtd.a lib/libopenthread-cli-mtd.a lib/libmbedtls.a lib/libopenthread-mtd.a lib/libtcplp.a lib/libopenthread-ftd.a lib/libopenthread-mtd.a lib/libtcplp.a lib/libopenthread-ftd.a lib/libmbedtls.a lib/libmbedx509.a lib/libmbedcrypto.a -Wl,--start-group ../third_party/Qorvo/repo/qpg6095/lib/libQorvoQPG6095_mtd.a -Wl,--end-group -T/home/runner/work/ot-qorvo/ot-qorvo/third_party/Qorvo/repo/qpg6095/ld/qpg6095.ld -nostdlib -Wl,--gc-sections -Wl,-Map=ot-cli-mtd.map,--cref && :
/tmp/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-writer.o): In function `_write_r':
writer.c:(.text._write_r+0x12): undefined reference to `_write'
/tmp/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-closer.o): In function `_close_r':
closer.c:(.text._close_r+0xc): undefined reference to `_close'
/tmp/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-fstatr.o): In function `_fstat_r':
fstatr.c:(.text._fstat_r+0x10): undefined reference to `_fstat'
/tmp/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-isattyr.o): In function `_isatty_r':
isattyr.c:(.text._isatty_r+0xc): undefined reference to `_isatty'
/tmp/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-lseekr.o): In function `_lseek_r':
lseekr.c:(.text._lseek_r+0x12): undefined reference to `_lseek'
/tmp/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-readr.o): In function `_read_r':
readr.c:(.text._read_r+0x12): undefined reference to `_read'
collect2: error: ld returned 1 exit status
[558/562] Building C object src/qpg6095/CMakeFiles/openthread-qpg6095-ftd.dir/radio.c.obj
[559/562] Building CXX object src/qpg6095/CMakeFiles/openthread-qpg6095-ftd.dir/settings.cpp.obj
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.
```

https://github.com/openthread/ot-qorvo/runs/4983155671?check_suite_focus=true

@thcu-gp @samkumar, can you help take a look?

**Comment by samkumar** [comment]
@jwhui Thanks for letting me know about this. I'll look into this over the weekend.

**Comment by samkumar** [comment]
@jwhui I've been looking into this today. Interestingly, I'm getting the same linker error you showed above when trying to build the main branch of `ot-qorvo`, with the `openthread` submodule still at commit `69ed42f4910253592b2a827a7b04b658b16fc384`. To verify that this is not an issue with my development environment, I installed a fresh Ubuntu 20.04 virtual machine, followed the instructions at https://github.com/Qorvo/qpg-openthread/blob/master/qpg6095/doc/README.md#getting-qorvo-openthread to build `openthread`. Unfortunately, I still found that building the current `main` branch of `ot-qorvo`, with the `openthread` submodule still at commit `69ed42f4910253592b2a827a7b04b658b16fc384`, fails with the error that you posted above. As a result, I'm unsure if the fix I have in mind actually resolves the issue.

In my setup, I observed that if I go back far enough in the commit history for `ot-qorvo`, I can find versions of the code that do build. Using `git bisect`, I identified `15fa4522d80c4e0039b5b25c6f4a12e1151000b8` as the commit that caused the `ot-qorvo` code to no longer build successfully in my setup. Do you have any thoughts as to why this might be the case?

I'm assuming you were able to build the current `main` branch, since you said you narrowed down the issue to a particular commit. I emailed you a patch file, which I suspect might fix the issue (unfortunately, GitHub does not let me attach a `.patch` file directly to this message). It's really a shot in the dark since I cannot validate locally whether this causes the build to succeed, but given that you can reproduce it, I figured that this might be worth a try.

**Comment by thcu-gp** [comment]
We can reproduces @jwhui debug process. We can build this up to the mentioned ot commit. The linker errors are indicative of the inclusion of stdlib. We do not include it in our builds.
Stubbing the calls, fixes the builds, but I can't tell if this has function consequences. 
@samkumar do you know where stdlib is included or where it is needed?

**Comment by jwhui** [comment]
@samkumar @thcu-gp , thanks for looking into this.

I have validated that the following change resolves the build issue:
```c++
--- a/third_party/tcplp/bsdtcp/tcp_output.c
+++ b/third_party/tcplp/bsdtcp/tcp_output.c
@@ -80,8 +80,8 @@ tcp_setpersist(struct tcpcb *tp)
        int tt;
 
        tp->t_flags &= ~TF_PREVVALID;
-       if (tcp_timer_active(tp, TT_REXMT))
-               printf("PANIC: tcp_setpersist: retransmit pending\n");
+//     if (tcp_timer_active(tp, TT_REXMT))
+//             printf("PANIC: tcp_setpersist: retransmit pending\n");
        /*
         * Start/restart persistance timer.
         */
@@ -1454,7 +1454,7 @@ tcp_addoptions(struct tcpopt *to, uint8_t *optp)
                        break;
                        }
                default:
-                       printf("PANIC: %s: unknown TCP option type", __func__);
+//                     printf("PANIC: %s: unknown TCP option type", __func__);
                        break;
                }
        }
```
No change is necessary to `bitmap.c` since nothing actually calls `bmp_print`.

Build log: https://github.com/jwhui/ot-qorvo/actions/runs/1774149414

@samkumar , would you like to submit PR?

**Comment by samkumar** [comment]
@thcu-gp The patch I sent Jonathan removed calls to `printf`. These calls were only made on assertion failures, so removing them wouldn't change any functionality. Based on Jonathan's reply, the patch worked and it was those calls to `printf` that was causing this. Like you mentioned, I suspected this based on the error messages (I recognized those functions as newlib stubs) but I wasn't entirely sure until Jonathan tested the patch, because OpenThread does use stdlib functions (e.g., `memset`, `memcpy`, `snprintf`, etc.). But now that we know what the problem is, we can move forward with a fix.

@jwhui Thanks for testing the patch that I sent you. I can submit a PR that appropriately handles this by calling into OpenThread to log assertion failures instead of calling `printf`. I'll try to submit that pull request at some point today.

**Comment by samkumar** [comment]
openthread/openthread#7379 should resolve this issue. It's better than the patch that I sent to Jonathan because it fixes the logging so that it happens correctly, via OpenThread, instead of just commenting it out.

@jwhui, please confirm that this resolves the build failure.

**Comment by jwhui** [comment]
> @jwhui, please confirm that this resolves the build failure.

I can confirm that this change addresses the build issue.

Build logs: https://github.com/jwhui/ot-qorvo/actions/runs/1774854431
